### ISSUE TITLE
Unicode for column url get error when title is in Chinese

### ISSUE THREAD

**Issue by ivesho** [matfish2/craft-activity-log#9]
** Versions **
Craft Pro 4.4.13
Activity Logs: 1.4.1

**Describe the bug**
I got the error message after entry created.
Only show when the title is in Chinese.

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xA4\xA4\xA4\xE5' for column `mocexpertdbcraft4`.`activitylog`.`url` at row 1 The SQL being executed was: INSERT INTO `activitylog` (`userId`, `url`, `query`, `payload`, `ip`, `userAgent`, `method`, `isAjax`, `isCp`, `siteId`, `isAction`, `actionSegments`, `createdAt`) VALUES (1, '/admin/entries/prepareExpertData/6156-����', NULL, NULL, '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36', 'GET', 0, 1, 1, 0, NULL, '2023-06-07 10:22:02')

**Screenshots**
![image](https://github.com/matfish2/craft-activity-log/assets/48641341/39da59a2-346b-47d3-9bb5-aadd9f391191)
![image](https://github.com/matfish2/craft-activity-log/assets/48641341/0a127f7b-6e93-47dd-9053-9d3ba2b6b4cb)

**Comment by matfish2** [comment]
Thank you for reporting @ivesho. I'll look into it and revert back asap.

**Comment by matfish2** [comment]
@ivesho I was unable to reproduce with Chinese characters, only with the string representation '\xA4\xA4\xA4\xE5'.
Added UTF-8 encoding to relevant columns (URL, query and payload).
Can you please change your `composer.json` to require:
```  
"matfish/craft-activity-log": "dev-hotfix/encoding",
```
And let me know if that solves the issue.

**Comment by ivesho** [comment]
Thank for your help. I tried to change, but it didn't respond. 

![image](https://github.com/matfish2/craft-activity-log/assets/48641341/2dc76134-1267-4d02-b56d-1c316ab234aa)

Maybe my system get something wrong, I will try again in next week, sorry.

if you want to copy chinese to try, this is example. 中文字

**Comment by matfish2** [comment]
Tried with 中文字 on original code. Unable to reproduce:
![chinese-activity-logs](https://github.com/matfish2/craft-activity-log/assets/1510460/2bdd26d5-331e-475c-a509-8da24f2f07ca)

Seems like the issue could be specifically the URL, as the Chinese characters are URL encoded by Craft (does not happen in payload, see slug).

While you are getting: \xA4\xA4\xA4\xE5
I am getting: %E4%B8%AD%E6%96%87%E5%AD%97 
Which seems the like the correct URL encoding.
Maybe something to do with your DB schema encoding?

At any rate can you please try to update using `composer.json` rather than `craft update`?
Replace
```
"matfish/craft-activity-log": "1.4.1",
```
with
```
"matfish/craft-activity-log": "dev-hotfix/encoding",
```
and run `composer update`

Thank you for your help in debugging this,

**Comment by matfish2** [comment]
Fixed
